config/routes.rb
Rails.application.routes.draw do
  resources :versions do
    resources :shared_hours, path: 'hours'
    resources :contract_works do
      member do
        post :update_issues
      end
      collection do
        post :sort
        get :for_version
      end
    end

  end

  resources :'reports' do
    member do
      put :approve
      put :reject
    end
    collection do
      get :export
    end
  end
end

app/models/contract_work.rb
# plugins/redmine_auto_report/app/models/contract_work.rb
class ContractWork < ActiveRecord::Base
  belongs_to :version
  has_many :issues
  has_one :contract_work_merge
  has_one :merged_hours, through: :contract_work_merge

  validates :name, presence: true
  validates :position, presence: true, numericality: { only_integer: true }
  validate :hours_validation

  before_validation :set_position

  def effective_hours
    merged_hours&.hours || planned_hours
  end

  private

  def hours_validation
    return true if planned_hours.present? || group_hours.present?
    errors.add(:base, :requires_hours)
  end

  def set_position
    if position.nil?
      max_position = version.contract_works.maximum(:position) || 0
      self.position = max_position + 1
    end
  end
end

app/controllers/contract_works_controller.rb
# plugins/redmine_auto_report/app/controllers/contract_works_controller.rb
class ContractWorksController < ApplicationController
  before_action :find_version
  before_action :find_work, only: [:edit, :update, :destroy]
  before_action :authorize_global

  def new
    @work = @version.contract_works.build
    respond_to do |format|
      format.js { render :new }
    end
  end

  def create
    @work = @version.contract_works.build(work_params)
    respond_to do |format|
      if @work.save
        @version.update_total_planned_hours
        format.js { render :refresh_list }
      else
        format.js { render :new }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def update
    respond_to do |format|
      if @work.update(work_params)
        @version.update_total_planned_hours
        format.js { render :refresh_list }
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @work.destroy
    @version.update_total_planned_hours
    respond_to do |format|
      format.js { render :refresh_list }
    end
  end

  def merge_hours
    works = @version.contract_works.where(id: params[:work_ids])
    total_hours = works.sum(:planned_hours)

    merged = MergedHours.create!(version: @version, hours: total_hours)
    works.each do |work|
      ContractWorkMerge.create!(merged_hours: merged, contract_work: work)
    end

    respond_to do |format|
      format.js { render :refresh_list }
    end
  end

  def unmerge_hours
    work = @version.contract_works.find(params[:work_id])
    merged = work.merged_hours
    if merged
      work.contract_work_merge.destroy
      merged.destroy if merged.contract_works.empty?
    end

    respond_to do |format|
      format.js { render :refresh_list }
    end
  end

  private

  def find_version
    @version = Version.find(params[:version_id])
    @project = @version.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_work
    @work = @version.contract_works.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def work_params
    params.require(:contract_work).permit(:name, :planned_hours)
  end
end

app/views/contract_works/_contextual_links.html.erb
<% if version.present? && User.current.allowed_to?(:manage_auto_reports, version.project) %>
  <%= link_to l(:label_contract_work_new),
              new_version_contract_work_path(version),
              class: 'icon icon-add',
              remote: true %>
<% end %>

app/views/contract_works/_form.html.erb
<%= form_for [@version, @work], remote: true, html: { class: 'tabular' } do |f| %>
  <%= error_messages_for @work %>

  <div class="box">
    <p>
      <%= f.label :name, l(:field_name) %><span class="required"> *</span>
      <%= f.text_field :name, size: 60, required: true %>
    </p>

    <p>
      <%= f.label :planned_hours, l(:field_planned_hours) %>
      <%= f.number_field :planned_hours, min: 0, step: 0.5 %>
    </p>
  </div>

  <%= f.submit @work.new_record? ? l(:button_create) : l(:button_save) %>
  <%= link_to l(:button_cancel), '#', class: 'js-cancel-form' %>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function() {
  $('.js-cancel-form').click(function(e) {
  e.preventDefault();
  $('#work-form').remove();
  $('#work-form-row-<%= @work.try(:id) %>').remove();
  });
  });
<% end %>

app/views/contract_works/_issues_form.html.erb
<!--# plugins/redmine_auto_report/app/views/contract_works/_issues_form.html.erb-->
<div class="box">
  <h3><%= l(:label_related_issues) %></h3>

  <% issues = @version.fixed_issues.where(contract_work_id: [nil, @work.id]) %>
  <% if issues.any? %>
    <%= form_tag update_issues_version_contract_work_path(@version, @work), remote: true do %>
      <table class="list issues">
        <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, class: 'toggle-selection' %>
          </th>
          <th>#</th>
          <th><%= l(:field_subject) %></th>
          <th><%= l(:field_status) %></th>
        </tr>
        </thead>
        <tbody>
        <% issues.each do |issue| %>
          <tr>
            <td class="checkbox hide-when-print">
              <%= check_box_tag 'issue_ids[]', issue.id, issue.contract_work_id == @work.id %>
            </td>
            <td class="id"><%= link_to issue.id, issue_path(issue) %></td>
            <td class="subject"><%= issue.subject %></td>
            <td class="status"><%= issue.status.name %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <p><%= submit_tag l(:button_save), class: 'small' %></p>
    <% end %>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>

app/views/contract_works/_list.html.erb
<!--# plugins/redmine_auto_report/app/views/contract_works/_list.html.erb-->
<div class="contextual">
  <%= link_to l(:button_merge_hours),
              merge_hours_version_contract_works_path(@version),
              class: 'icon icon-link merge-hours',
              style: 'display: none',
              remote: true %>
  <%= link_to l(:button_unmerge_hours),
              unmerge_hours_version_contract_works_path(@version),
              class: 'icon icon-unlink unmerge-hours',
              style: 'display: none',
              remote: true %>
</div>

<table class="list contract-works">
  <thead>
  <tr>
    <th>#</th>
    <th><%= l(:field_name) %></th>
    <th><%= l(:field_hours) %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @version.contract_works.each do |work| %>
    <tr class="work <%= 'merged' if work.merged_hours.present? %>"
        data-id="<%= work.id %>">
      <td class="position"><%= work.position %></td>
      <td class="name"><%= h work.name %></td>
      <td class="hours <%= 'merged' if work.merged_hours.present? %>">
        <%= h work.effective_hours %>
      </td>
      <td class="buttons">
        <%= link_to l(:button_edit),
                    edit_version_contract_work_path(@version, work),
                    remote: true,
                    class: 'icon icon-edit' %>
        <%= link_to l(:button_delete),
                    version_contract_work_path(@version, work),
                    method: :delete,
                    remote: true,
                    class: 'icon icon-del',
                    data: { confirm: l(:text_are_you_sure) } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/contract_works/_total_hours.html.erb
<div class="total-hours">
  <%= l(:label_total_planned_hours) %>:
  <span class="hours"><%= h @version.total_planned_hours %></span>
</div>

app/views/contract_works/_work.html.erb
<tr class="work <%= 'grouped' if work.work_group.present? %>" id="work-<%= work.id %>">
  <td class="position"><%= work.position %></td>
  <td class="name">
    <%= h work.name %>
    <% if work.work_group.present? %>
      <div class="group-info">
        <%= l(:label_group) %>: <%= work.work_group %>
        (<%= work.group_hours %>)
      </div>
    <% end %>
  </td>
  <td class="hours">
    <%= work.planned_hours if work.planned_hours.present? %>
  </td>
  <td class="issues">
    <%= work.issues.count %>
  </td>
  <td class="buttons">
    <%= link_to l(:button_edit),
                edit_version_contract_work_path(@version, work),
                remote: true,
                class: 'icon icon-edit' %>
    <%= link_to l(:button_delete),
                version_contract_work_path(@version, work),
                method: :delete,
                remote: true,
                class: 'icon icon-del',
                data: { confirm: l(:text_are_you_sure) } %>
  </td>
</tr>

app/views/contract_works/create.js.erb
<% if @work.valid? %>
$("#contract-works").replaceWith("<%= j render partial: 'versions/contract_works_list' %>");
$("#work-form").remove();
<% else %>
$("#work-form").html("<%= j render('form') %>");
<% end %>

app/views/contract_works/destroy.js.erb
$("#contract-works").replaceWith("<%= j render partial: 'versions/contract_works_list' %>");

app/views/contract_works/edit.js.erb
$("#work-<%= @work.id %>").replaceWith("<tr id='work-form-row-<%= @work.id %>'><td colspan='4'><div id='work-form' class='box tabular'><%= j render('form') %></div></td></tr>");

app/views/contract_works/merge_hours.js.erb
location.reload();

app/views/contract_works/new.js.erb
$("#work-form").remove();
$(".contract-works-list").after("<div id='work-form' class='box tabular'><%= j render('form') %></div>");

app/views/contract_works/refresh_list.js.erb
$("#contract-works").html("<%= j render partial: 'versions/contract_works_list' %>");

app/views/contract_works/unmerge_hours.js.erb
location.reload();

app/views/contract_works/update.js.erb
<% if @work.valid? %>
$("#contract-works").replaceWith("<%= j render partial: 'versions/contract_works_list' %>");
$("#work-form-row-<%= @work.id %>").remove();
<% else %>
$("#work-form-row-<%= @work.id %> td").html("<%= j render('form') %>");
<% end %>